# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atendentes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atendentes(object):
    def setupUi(self, atendentes):
        atendentes.setObjectName("atendentes")
        atendentes.resize(800, 600)
        atendentes.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"font-size: 15px\n"
"}\n"
"\n"
"QMainWindow{\n"
"background:black;\n"
"}\n"
"\n"
"QLabel{\n"
"color: white;\n"
"font-size: 40px\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"background: transparent;\n"
"border-radius: 5px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(atendentes)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 360, 571, 121))
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(380, 110, 281, 211))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(200, 200))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(70, 80, 381, 311))
        self.toolButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/multi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(500, 500))
        self.toolButton_2.setObjectName("toolButton_2")
        atendentes.setCentralWidget(self.centralwidget)

        self.retranslateUi(atendentes)
        QtCore.QMetaObject.connectSlotsByName(atendentes)

    def retranslateUi(self, atendentes):
        _translate = QtCore.QCoreApplication.translate
        atendentes.setWindowTitle(_translate("atendentes", "Em construção"))
        self.label.setText(_translate("atendentes", "ÁREA EM DESENVOLVIMENTO"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_atendentes()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
