# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_Cadastro(object):
    def cadastrar(self):
        try:       
            nome = self.lineEdit.text()
            login = self.lineEdit_3.text()
            senha = self.lineEdit_2.text()
            c_senha = self.lineEdit_4.text()
            if (self.checkBox.isChecked()):
                priv = 'backoffice'
            if (self.checkBox_2.isChecked()):
                priv = 'atendente'
            if (self.checkBox_3.isChecked()):
                priv = 'admin'
            if (senha == c_senha):    
                try:
                    banco = sqlite3.connect('bdCadastro.db') 
                    cursor = banco.cursor()
                    cursor.execute("CREATE TABLE IF NOT EXISTS cadastro (nome text,login text,senha text,priv text)")
                    cursor.execute("INSERT INTO cadastro VALUES ('"+nome+"','"+login+"','"+senha+"','"+priv+"')")
                    banco.commit() 
                    banco.close()
                    
                    self.msg = QMessageBox()
                    self.msg.setWindowTitle('Sistema de cadastro')
                    self.msg.setIcon(QMessageBox.Information)
                    self.msg.setText("Usuário criado com sucesso!")
                    self.msg.exec_()

                except sqlite3.Error as erro:
                    self.msg = QMessageBox()
                    self.msg.setIcon(QMessageBox.Warning)
                    self.msg.setWindowTitle('Erro.')
                    self.msg.setText("Erro ao inserir dados. Verifique erros abaixo:")
                    self.msg.setDetailedText(str(erro))
                    self.msg.exec_()
            else:
                self.msg = QMessageBox()
                self.msg.setWindowTitle('Erro.')
                self.msg.setIcon(QMessageBox.Information)
                self.msg.setText("As senhas digitadas possuem diferenças entre si.")
                self.msg.exec_()
        except Exception as e:
            print(e)
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.setFixedSize(551, 607)
        Cadastro.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"font-size: 15px\n"
"}\n"
"\n"
"#label_2\n"
"{\n"
"font-size: 24px\n"
"}\n"
"\n"
"QMainWindow{\n"
"background:url(img/background.jpeg);\n"
"}\n"
"QFrame\n"
"{\n"
"background: rgba(0,0,0,0.8);\n"
"border-radius: 5px\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"color: #333;\n"
"background: white;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"color: 333;\n"
"background: gray;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QToolButton\n"
"{\n"
"background: white;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"color: white;\n"
"background: transparent;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background: transparent;\n"
"border: none;\n"
"color: #717072;\n"
"border-bottom: 1px solid #717072;\n"
"}\n"
"\n"
"QRadioButton\n"
"{\n"
"color: white\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(10, 10, 531, 111))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.label_2 = QtWidgets.QLabel(self.header)
        self.label_2.setGeometry(QtCore.QRect(120, 50, 651, 41))
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(self.header)
        self.toolButton.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/multi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setObjectName("toolButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 130, 531, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 390, 451, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.cadastrar)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 50, 451, 41))
        self.lineEdit.setText("")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 190, 451, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 191, 31))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 211, 31))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 120, 451, 41))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 100, 191, 31))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 240, 211, 31))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 260, 451, 41))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(150, 300, 261, 41))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QRadioButton(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(100, 350, 131, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QRadioButton(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(220, 350, 131, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QRadioButton(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 350, 131, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        Cadastro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)

    def retranslateUi(self, Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Cadastro.setWindowTitle(_translate("Cadastro", "Cadastro"))
        self.label_2.setText(_translate("Cadastro", "Cadastro de usuários"))
        self.pushButton.setText(_translate("Cadastro", "Criar novo usuário"))
        self.lineEdit.setPlaceholderText(_translate("Cadastro", "Nome do Usuário"))
        self.lineEdit_2.setPlaceholderText(_translate("Cadastro", "Senha"))
        self.label_3.setText(_translate("Cadastro", "Nome do Usuário"))
        self.label_4.setText(_translate("Cadastro", "Senha"))
        self.lineEdit_3.setPlaceholderText(_translate("Cadastro", "Login"))
        self.label_6.setText(_translate("Cadastro", "Login"))
        self.label_5.setText(_translate("Cadastro", "Repita a senha"))
        self.lineEdit_4.setPlaceholderText(_translate("Cadastro", "Senha"))
        self.label_7.setText(_translate("Cadastro", "Nível de privilégio do novo usuário:"))
        self.checkBox.setText(_translate("Cadastro", "Backoffice"))
        self.checkBox_2.setText(_translate("Cadastro", "Atendente"))
        self.checkBox_3.setText(_translate("Cadastro", "Administrador"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastro = QtWidgets.QMainWindow()
    ui = Ui_Cadastro()
    ui.setupUi(Cadastro)
    Cadastro.show()
    sys.exit(app.exec_())
